import {
  Heading,
  Stack,
  Center,
  Box,
  Text,
  Badge,
  Flex,
  Spacer,
} from "@chakra-ui/layout";
import {
  Tag,
} from "@chakra-ui/react"
import { Avatar } from "@chakra-ui/avatar";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "../../constants/axios";
import Link from "next/link";
import { Spot } from "../../types/spot";
import { LinkBox, LinkOverlay } from "@chakra-ui/react";
import formatDistanceToNow from "date-fns/formatDistanceToNow";
import { ja } from "date-fns/locale";

export const getServerSideProps = async () => {
  const res = await axios.get("/api/spots/");
  const spots = res.data;
  return {
    props: {
      spots,
    },
  };
};

type Props = {
  spots: Spot[];
};

const SpotIndex: React.FC<Props> = ({ spots }) => {
  console.log(spots);
  return (
    <div>
      <Head>
        <title>SkateSpot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Center>
          <Stack p={8} w="lg">
            <Heading>スポット一覧</Heading>
            {spots.map((spot) => {
              const date = new Date(spot.created_at);
              console.log(date);
              return (
                <Link key={spot.id} href="/spot/[id]" as={`/spot/${spot.id}`}>
                  <Box borderWidth="1px" rounded={"md"} p={5}>
                    <Heading size="md" mb={5}>
                      <Tag
                        colorScheme="purple"
                        mr="2"
                      >
                        {spot.prefectures}
                      </Tag>
                      {spot.name}
                    </Heading>
                    <Flex align="center">
                      <Avatar
                        size="sm"
                        mr="2"
                        src=""
                      />
                      <Text>{spot.user.name}</Text>
                      <Spacer/>
                      <Text fontSize="xs">
                        {formatDistanceToNow(date, {
                          addSuffix: true,
                          locale: ja,
                        })}
                      </Text>
                    </Flex>
                  </Box>
                </Link>
              );
            })}
          </Stack>
        </Center>
      </main>
    </div>
  );
};
export default SpotIndex;
